#!/bin/sh

if [ -z "$1" ];then
    echo "USAGE: $0 BinNumber
Convert binary number to decimal number" 1>&2
    exit 1
else
    if [ $1 -lt 0 ]; then
	num=`expr 0 - $1`
    else
	num=$1
    fi
    val=$num
    test=1
    while [ $val -gt 0 ]; do
	if [ `expr $val % 10` -gt 1 ]; then
	    test=0
	fi
	val=`expr $val / 10`
    done
    if [ $test -le 0 ]; then
	echo "Error" 1>&2
	exit 1
    else
	if [ $1 -lt 0 ]; then
	    echo "bin2dec($1)=-$((2#$num))"
	else
	    echo "bin2dec($1)=$((2#$num))"
	fi
	exit 0
    fi
fi
