#!/bin/sh

if [ -z "$1" ];then
    echo "USAGE: $0 number
Compute factorial of a number" 1>&2
    exit 1
else
    if [ $1 -lt 0 ]; then
	echo "Error" 1>&2
	exit 1	
    else
	i=0
	fact=1
	while [ $i -lt $1 ]; do
	    i=`expr $i + 1`
	    fact=`expr $fact \* $i` 
	done
	echo "$fact"
	exit 0
    fi
fi
