#!/bin/sh

if [ -z "$1" ];then
    echo "USAGE: $0 n
Display n first primary number" 1>&2
    exit 1
else
    if [ $1 -lt 0 ]; then
	echo "ERROR" 1>&2
	exit 1 
    else
	i=2
	c=0
	while [ $c -lt $1 ]; do
	    j=2
	    prime=1
	    while [ $j -lt `expr $i - 1` ] && [ $prime -eq 1 ]; do
		if [ `expr $i % $j` -eq 0 ]; then
		    prime=0
		fi
		j=`expr $j + 1`
	    done
	    if [ $prime -eq 1 ]; then
		if [ $c -eq `expr $1 - 1` ]; then
		    echo "$i"
		else
		    echo -n "$i "
		fi
		c=`expr $c + 1`
	    fi
	    i=`expr $i + 1`
	done
	exit 0
    fi
fi
